services:
  postgres:
    image: postgres:16

    container_name: devops-postgres

    restart: always

    environment:
      POSTGRES_DB: devops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d devops"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .

    container_name: devops-backend

    restart: always

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/devops

    ports:
      - "8000:8000"

volumes:
  postgres_data:
    name: devops-postgres-data